# Generated by Django 2.2.5 on 2021-02-14 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='comments',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='provision_type',
            field=models.IntegerField(choices=[(0, 'Delivery'), (1, 'Pick-up/Drop-off')]),
        ),
        migrations.AlterField(
            model_name='order',
            name='retrieval_type',
            field=models.IntegerField(choices=[(0, 'Delivery'), (1, 'Pick-up/Drop-off')]),
        ),
    ]
