# Generated by Django 2.2.5 on 2021-02-14 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20210214_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='service',
            field=models.IntegerField(choices=[(0, 'Wash and Dry'), (1, 'Wash, Dry, and Fold'), (2, 'Dry Cleaning'), (3, 'Laundromat Products'), (4, 'Wash'), (5, 'Dry'), (6, 'Fold'), (7, 'Spin Dry')]),
        ),
    ]
