# Generated by Django 2.2.5 on 2021-02-14 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20210214_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='provision_type',
            field=models.IntegerField(choices=[(0, 'Delivery'), (1, 'Drop-off')]),
        ),
        migrations.AlterField(
            model_name='order',
            name='retrieval_type',
            field=models.IntegerField(choices=[(0, 'Delivery'), (1, 'Pick-up')]),
        ),
    ]
